<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>Latest</LangVersion>
    <RazorLangVersion>8.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.39.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0"/>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/"/> <!--    readme from the repository root-->
    <None Include="../BlazorStaticWebsite/wwwroot/imgs/logo.png" Pack="true" PackagePath="/BlazorStaticWebsite/wwwroot/imgs/"/><!--    logo to match what is inside the readme.md-->
  </ItemGroup>

  <PropertyGroup>
    <Authors>tesar.tech</Authors>
    <Product>BlazorStatic</Product>
    <Description>Static site generator for Blazor</Description>
    <PackageId>BlazorStatic</PackageId>
    <Version Condition="'$(EnvironmentName)' != 'Development'">1.0.0-beta.15</Version>
    <!--Set EnvironmentName using dotnet build -c Release -p:EnvironmentName=Development for local package build-->
    <Version Condition="'$(EnvironmentName)' == 'Development'">1.0.0-dev.$([System.DateTime]::Now.ToString("yyMMddHHmmss"))</Version>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/BlazorStatic/BlazorStatic/</RepositoryUrl>
    <PackageProjectUrl>https://blazorstatic.net</PackageProjectUrl>
    <PackageTags>Blazor, StaticSiteGenerator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>

  </PropertyGroup>

  <Target Name="CustomAfterBuild" AfterTargets="Build">
    <Message Importance="High" Text="AfterBuild: creating Dependencies folder"/>
    <MakeDir Directories="$(ProjectDir)..\..\koskilanet-blazorstatic\web\Dependencies"/>
    <Message Importance="High" Text="AfterBuild: copying BlazorStatic.dll"/>
    <Message Importance="High" Text="AfterBuild: DestinationFolder = $(ProjectDir)..\..\koskilanet-blazorstatic\web\Dependencies"/>
    <Copy
      SourceFiles="$(TargetDir)BlazorStatic.dll"
      DestinationFolder="$(ProjectDir)..\..\koskilanet-blazorstatic\web\Dependencies"
      OverwriteReadOnlyFiles="true"/>
    <Message Importance="High" Text="AfterBuild: copy complete"/>
  </Target>

</Project>
